version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifats:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes